#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Download openwrt
        run: |
          git clone https://github.com/openwrt/openwrt.git
          mv ./openwrt/* ./
      - name: Update luci feeds
        run: |
          ./scripts/feeds update luci
          ./scripts/feeds install -a -p luci
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Gen openwrt configure file
        run: |
          make defconfig
      - name: Custom openwrt configure file
        run: |
          echo CONFIG_TARGET_armvirt=y >> .config
          echo CONFIG_TARGET_armvirt_64=y >> .config
          echo CONFIG_TARGET_armvirt_64_Default=y >> .config
          echo CONFIG_TARGET_BOARD="armvirt" >> .config
          echo CONFIG_TARGET_PROFILE=y >> .config
          echo CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53" >> .config
          echo CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mcpu=cortex-a53" >> .config
          echo CONFIG_CPU_TYPE="cortex-a53" >> .config
          echo CONFIG_LINUX_5_15=y >> .config
          echo CONFIG_TARGET_ROOTFS_INITRAMFS=y >> .config
          
          echo CONFIG_TARGET_ROOTFS_EXT4FS=y >> .config
          echo CONFIG_TARGET_ROOTFS_INITRAMFS=y >> .config
          
      - name: Custom linux configure file
        run: |
          echo CONFIG_EFI=y >> ./target/linux/armvirt/64/config-5.15
          echo CONFIG_EFI_STUB=y >> ./target/linux/armvirt/64/config-5.15
          echo CONFIG_EFI_EALYCON=y >> ./target/linux/armvirt/64/config-5.15
          echo CONFIG_ACPI=y >> ./target/linux/armvirt/64/config-5.15
          
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: bin/targets/
          
